export const categoryToCountryMap: Record<string, string> = {
  Brazilian: "Brazil",
  Chinese: "China",
  Japanese: "Japan",
  Indian: "India",
  Greek: "Greece",
  Mexican: "Mexico",
  Italian: "Italy",
  French: "France",
  German: "Germany",
  Korean: "Republic of Korea",
  Hungarian: "Hungary",
  Dutch: "Netherlands",
  Cuban: "Cuba",
  Moroccan: "Morocco",
  Portuguese: "Portugal",
  Polish: "Poland",
  Russian: "Russian Federation",
  Swedish: "Sweden",
  Spanish: "Spain",
  Turkish: "Turkey",
  Vietnamese: "Viet Nam",
  Lebanese: "Lebanon",
  "South African": "South Africa",
  Canadian: "Canada",
  Pakistani: "Pakistan",
  Egyptian: "Egypt",
  Chilean: "Chile",
  "New Zealand": "New Zealand",
  Norwegian: "Norway",
  Australian: "Australia",
  Thai: "Thailand",
  "Tex Mex": "United States of America",
  "Native American": "United States of America",
};
